from tests.test_postgres_transfer import postgres,schema
from tests.test_postgres_http import configured,client
from tests.test_validation import lab
from tests.test_goal_selection import (
    test_selected_goal_round_skips_other_asset_retains_coverage_and_cumulative_progress as test_native_selected_goal_round,
    test_goal_selection_survives_replan_retry_and_same_request_replay as test_native_selected_goal_attempts,
    test_invalid_or_removed_goal_selection_cannot_be_approved as test_native_goal_selection_tamper,
    test_goal_todo_repeats_only_requested_pairs_and_records_repeated_completion as test_native_goal_selection_todo,
    test_goal_selection_changed_after_approval_fails_contract_before_execution as test_native_goal_selection_approval_contract,
    test_scope_change_invalidates_selection_review_and_revalidates_only_stale_pairs as test_native_goal_selection_scope_change,
    test_damaged_approved_selection_blocks_accepted_request_replay_without_erasing_results as test_native_goal_selection_replay_tamper,
)
