from tests.test_postgres_transfer import postgres,schema
from tests.test_postgres_http import configured,client
from tests.test_validation import lab
from tests.test_observation_todos import (
 test_observation_failure_automatically_records_one_note_and_no_tool_request as test_native_observation_note,
 test_automatic_observation_note_does_not_overwrite_human_edit_or_completion as test_native_observation_note_human,
 test_automatic_note_and_review_cursor_audit_roll_back_together_then_replay as test_native_observation_note_recovery,
 test_proposal_reviewed_before_automatic_note_is_stale_after_atomic_recording as test_native_observation_note_stale,
 test_damaged_automatic_origin_blocks_replay_without_overwriting_record as test_native_observation_note_damage,
 test_legacy_processing_position_replays_failure_events_after_upgrade as test_native_observation_note_upgrade,
 test_automatic_note_context_limit_is_visible_without_poisoning_proposal as test_native_observation_note_limit,
)
