from tests.test_postgres_transfer import postgres,schema
from tests.test_postgres_http import configured,client
from tests.test_validation import lab
from tests.test_goal_observations import (
    test_goal_observation_filters_asset_and_declared_checks_then_executes_only_selected_url as test_native_goal_observation,
    test_goal_observation_rejects_outside_or_changed_objective_without_requests as test_native_goal_observation_reject,
    test_goal_observation_replan_retry_preserve_objective_and_require_fresh_approval as test_native_goal_observation_attempts,
    test_goal_observation_metadata_tampering_blocks_approval_and_request_replay as test_native_goal_observation_tamper,
    test_goal_observation_final_write_rechecks_goal_and_rolls_back_records as test_native_goal_observation_write_race,
    test_goal_observation_removed_reference_blocks_replay_and_approval as test_native_goal_observation_removed,
    test_goal_observation_viewer_can_review_but_cannot_create as test_native_goal_observation_viewer,
)
