"""Offline, atomic storage transfer. PostgreSQL service execution is not enabled yet."""
import hashlib
import json
import os
import re
import sqlite3
import tempfile
from decimal import Decimal
from contextlib import closing
from pathlib import Path

from .audit import verify_chain
from .backups import readonly, validate_backup
from .maintenance import WorkspaceLease
from .migrations import SCHEMA_VERSION, migrate

FORMAT = 'aegis-postgres-storage-v1'
TABLES = {
    'records': ('rowid','kind','id','data'),
    'users': ('id','username','name','role','salt','password_hash','disabled','created_at','updated_at'),
    'events': ('seq','ts','task_id','level','message','detail'),
    'event_hashes': ('seq','previous_hash','event_hash'),
    'audit_state': ('id','chain_id','last_seq','head_hash','sealed_legacy_until'),
}
ORDER = {'records':'rowid','users':'id','events':'seq','event_hashes':'seq','audit_state':'id'}
DDL = (
    'CREATE TABLE records (rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE, kind TEXT NOT NULL, id TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(kind,id))',
    "CREATE TABLE users (id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','operator','viewer')), salt TEXT NOT NULL, password_hash TEXT NOT NULL, disabled INTEGER NOT NULL DEFAULT 0, created_at DOUBLE PRECISION NOT NULL, updated_at DOUBLE PRECISION NOT NULL)",
    'CREATE TABLE sessions (digest TEXT PRIMARY KEY, expires DOUBLE PRECISION NOT NULL, user_id TEXT NOT NULL REFERENCES users(id))',
    'CREATE TABLE events (seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts DOUBLE PRECISION NOT NULL, task_id TEXT, level TEXT, message TEXT, detail TEXT)',
    'CREATE TABLE event_hashes (seq BIGINT PRIMARY KEY REFERENCES events(seq), previous_hash TEXT NOT NULL, event_hash TEXT NOT NULL)',
    'CREATE TABLE audit_state (id INTEGER PRIMARY KEY CHECK(id=1), chain_id TEXT NOT NULL, last_seq BIGINT NOT NULL, head_hash TEXT NOT NULL, sealed_legacy_until BIGINT NOT NULL)',
    'CREATE TABLE storage_metadata (id INTEGER PRIMARY KEY CHECK(id=1), format TEXT NOT NULL, sqlite_schema INTEGER NOT NULL, event_sequence BIGINT NOT NULL)',
    'CREATE INDEX events_task_seq ON events(task_id,seq)',
    'CREATE INDEX sessions_user ON sessions(user_id)',
)


class TransferError(ValueError):
    pass


def driver():
    try:
        import psycopg
        from psycopg import sql
        from psycopg.rows import dict_row
    except ImportError:
        raise TransferError('PostgreSQL 전송에는 open-aegis[postgres] 설치가 필요합니다.') from None
    return psycopg, sql, dict_row


def validate_schema(schema):
    if (not isinstance(schema,str) or not re.fullmatch('[a-z][a-z0-9_]{0,62}',schema)
            or schema == 'public' or schema.startswith('pg_') or schema == 'information_schema'):
        raise TransferError('별도의 새 PostgreSQL 스키마 이름을 지정하세요.')


def connect(dsn):
    psycopg, _, factory = driver()
    if not isinstance(dsn,str) or not dsn.strip():
        raise TransferError('AEGIS_POSTGRES_DSN 연결 설정이 필요합니다.')
    return psycopg.connect(dsn,autocommit=True,row_factory=factory,connect_timeout=5,
                           options='-c statement_timeout=120000 -c lock_timeout=5000')


def set_schema(db,schema):
    _,sql,_=driver()
    db.execute(sql.SQL('SET LOCAL search_path TO pg_catalog, {}').format(sql.Identifier(schema)))


def digest_rows(rows,columns):
    digest=hashlib.sha256();count=0
    for row in rows:
        values=[row[key] for key in columns] if hasattr(row,'keys') else list(row)
        if columns == TABLES['records']:
            try:
                json.loads(values[-1],parse_float=Decimal,parse_constant=lambda value: (_ for _ in ()).throw(ValueError(value)))
            except (ValueError,RecursionError):
                raise TransferError('기록 JSON을 엄격하게 읽을 수 없습니다.') from None
        payload=json.dumps(values,ensure_ascii=False,separators=(',',':'),allow_nan=False).encode('utf-8')
        digest.update(len(payload).to_bytes(8,'big'));digest.update(payload);count+=1
    return {'rows':count,'sha256':digest.hexdigest()}


def sqlite_manifest(db):
    return {table:digest_rows(db.execute(f'SELECT {",".join(columns)} FROM {table} ORDER BY {ORDER[table]}'),columns)
            for table,columns in TABLES.items()}


def postgres_manifest(db):
    # Server-side cursors bound client memory regardless of history size.
    result={}
    for table,columns in TABLES.items():
        with db.cursor(name='aegis_'+table) as cursor:
            cursor.execute(f'SELECT {",".join(columns)} FROM {table} ORDER BY ' + ("id COLLATE \"C\"" if table=='users' else ORDER[table]))
            result[table]=digest_rows(cursor,columns)
    return result


def postgres_audit(db, checkpoint=None):
    class Reader:
        stream=None
        def execute(self,query):
            if query.startswith('SELECT e.*,h.previous_hash'):
                self.stream=db.cursor(name='aegis_audit_verification')
                self.stream.execute(query)
                return self.stream
            return db.execute(query)
    reader=Reader()
    try:
        return verify_chain(reader,checkpoint)
    finally:
        if reader.stream is not None: reader.stream.close()


def validate_postgres(db, *, require_empty_sessions=True):
    row=db.execute('SELECT * FROM storage_metadata WHERE id=1').fetchone()
    if (not row or row['format']!=FORMAT or row['sqlite_schema']!=SCHEMA_VERSION
            or type(row['event_sequence']) is not int or row['event_sequence']<0):
        raise TransferError('지원하지 않는 PostgreSQL 저장 형식입니다.')
    sessions=db.execute('SELECT count(*) AS count FROM sessions').fetchone()['count']
    if require_empty_sessions and sessions:
        raise TransferError('전송 스키마에 세션이 있습니다. 실행 저장소의 오프라인 내보내기 계약이 필요합니다.')
    audit=postgres_audit(db)
    maximum=db.execute('SELECT coalesce(max(seq),0) AS seq FROM events').fetchone()['seq']
    if row['event_sequence']<maximum:
        raise TransferError('감사 이벤트 순서 기준이 올바르지 않습니다.')
    # PostgreSQL identity allocation is not rolled back with a failed write.
    # Preserve its high water mark, including uncommitted allocations, on return.
    sequence=db.execute("SELECT n.nspname,c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.oid=pg_get_serial_sequence('events','seq')::regclass").fetchone()
    if not sequence:
        raise TransferError('감사 이벤트의 순번 할당기가 없습니다.')
    _,sql,_=driver()
    allocated=db.execute(sql.SQL('SELECT last_value,is_called FROM {}').format(sql.Identifier(sequence['nspname'],sequence['relname']))).fetchone()
    row={**row,'event_sequence':max(row['event_sequence'],allocated['last_value'] if allocated['is_called'] else 0),'session_count':sessions}
    return row,audit


def sqlite_to_postgres(source,dsn,schema):
    """Fresh schema only. Failure rolls back DDL and copied data together."""
    validate_schema(schema);source=Path(source).resolve(strict=True)
    _,sql,_=driver()
    with WorkspaceLease(source.parent), closing(readonly(source)) as src:
        src.row_factory=sqlite3.Row;src.execute('BEGIN')
        metadata=validate_backup(source)
        if metadata['schema_version']!=SCHEMA_VERSION:
            raise TransferError('먼저 현재 SQLite 스키마로 업그레이드하세요.')
        if src.execute("SELECT 1 FROM records WHERE kind='tasks' AND json_extract(data,'$.status') IN ('queued','running','stopping') LIMIT 1").fetchone():
            raise TransferError('실행 중이거나 대기 중인 작업이 있어 전송할 수 없습니다.')
        audit=verify_chain(src);expected=sqlite_manifest(src)
        sequence=src.execute("SELECT seq FROM sqlite_sequence WHERE name='events'").fetchone()
        event_sequence=sequence[0] if sequence else 0
        sessions=src.execute('SELECT count(*) FROM sessions').fetchone()[0]
        with connect(dsn) as target, target.transaction():
            target.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(schema)))
            set_schema(target,schema)
            qualified=sql.Identifier(schema).as_string(target)
            # pg_catalog is first for reads; explicitly qualify CREATE destinations.
            for statement in DDL:
                tokens=statement.split(' ')
                if tokens[1]=='TABLE':
                    statement=statement.replace(tokens[2],qualified+'.'+tokens[2],1)
                else:
                    statement=statement.replace(' ON ',' ON '+qualified+'.',1)
                target.execute(statement)
            for table,columns in TABLES.items():
                with target.cursor() as cursor, cursor.copy(f'COPY {qualified}.{table} ({",".join(columns)}) FROM STDIN') as copy:
                    for row in src.execute(f'SELECT {",".join(columns)} FROM {table} ORDER BY {ORDER[table]}'):
                        copy.write_row(tuple(row))
            target.execute('INSERT INTO storage_metadata VALUES (1,%s,%s,%s)',(FORMAT,SCHEMA_VERSION,event_sequence))
            for table,column,maximum in [('records','rowid',max(0,src.execute('SELECT coalesce(max(rowid),0) FROM records').fetchone()[0])),('events','seq',event_sequence)]:
                target.execute('SELECT setval(pg_get_serial_sequence(%s,%s),%s,%s)',(qualified+'.'+table,column,max(1,maximum),maximum>0))
            _,verified=validate_postgres(target)
            actual=postgres_manifest(target)
            if actual!=expected or verified['checkpoint']!=audit['checkpoint']:
                raise TransferError('PostgreSQL 전송 후 데이터 검증이 일치하지 않습니다.')
        return {'format':FORMAT,'schema':schema,'manifest':expected,'audit':audit,
                'sessions_revoked':sessions,'service_backend_enabled':False}


def postgres_to_sqlite(dsn,schema,output):
    """Validated new SQLite file; never replace an existing workspace/database."""
    validate_schema(schema);output=Path(output).absolute()
    output.parent.mkdir(parents=True,exist_ok=True)
    if output.exists() or output.is_symlink():
        raise TransferError('출력 경로가 이미 존재합니다.')
    with WorkspaceLease(output.parent):
        stage=None
        try:
            with connect(dsn) as src, src.transaction():
                src.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY')
                set_schema(src,schema)
                from .postgres_maintenance import offline_export
                offline_export(src,schema)
                # Refuse views/extra tables instead of executing an arbitrary stored view.
                objects=src.execute('SELECT c.relname,c.relkind FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=%s AND c.relkind IN (\'r\',\'v\',\'m\',\'f\',\'p\')',(schema,)).fetchall()
                if {row['relname'] for row in objects}!=set(TABLES)|{'sessions','storage_metadata'} or any(row['relkind']!='r' for row in objects):
                    raise TransferError('PostgreSQL 전송 스키마의 테이블 구성이 다릅니다.')
                metadata,audit=validate_postgres(src,require_empty_sessions=False);expected=postgres_manifest(src)
                fd,temporary=tempfile.mkstemp(prefix='.pg-transfer-',suffix='.db',dir=output.parent);os.close(fd)
                stage=Path(temporary)
                migrate(stage)
                with closing(sqlite3.connect(stage)) as target:
                    target.execute('PRAGMA foreign_keys=ON');target.execute('BEGIN IMMEDIATE')
                    target.execute('DELETE FROM audit_state')
                    for table,columns in TABLES.items():
                        with src.cursor(name='export_'+table) as cursor:
                            cursor.execute(f'SELECT {",".join(columns)} FROM {table} ORDER BY ' + ("id COLLATE \"C\"" if table=='users' else ORDER[table]))
                            for row in cursor:
                                target.execute(f'INSERT INTO {table} ({",".join(columns)}) VALUES ({",".join("?" for _ in columns)})',tuple(row[key] for key in columns))
                    target.execute("DELETE FROM sqlite_sequence WHERE name='events'")
                    target.execute("INSERT INTO sqlite_sequence VALUES ('events',?)",(metadata['event_sequence'],))
                    target.commit();target.row_factory=sqlite3.Row
                    if sqlite_manifest(target)!=expected or verify_chain(target)['checkpoint']!=audit['checkpoint']:
                        raise TransferError('SQLite로 되돌린 데이터 검증이 일치하지 않습니다.')
                validate_backup(stage)
                with stage.open('rb') as file:os.fsync(file.fileno())
            # Close the read transaction and connection before publishing any output.
            # Hard-link publication cannot overwrite a concurrent creator, unlike replace().
            os.link(stage,output)
            directory=os.open(output.parent,os.O_RDONLY)
            try:os.fsync(directory)
            finally:os.close(directory)
        finally:
            if stage is not None: stage.unlink(missing_ok=True)
        return {'format':FORMAT,'schema':schema,'manifest':expected,'audit':audit,
                'sessions_revoked':True,'omitted_session_count':metadata['session_count'],
                'source_sessions_preserved':True,'output':str(output),'service_backend_enabled':False}
